[package]
name = "basic-btc-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
clap = {version = "4.5.27", features = ["derive"]}
hex = "0.4.3"
k256 = {version = "0.13.4", features = ["ecdsa"]}
ripemd = "0.1.3"
sha2 = "0.10.8"
tiny-bip39 = "2.0.0"
